-- MySQL Script generated by MySQL Workbench
-- Mon May 13 16:47:16 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`catalog_UserType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`catalog_UserType` (
  `Id` INT NOT NULL,
  `Detail` VARCHAR(100) NOT NULL,
  `Date` DATETIME NOT NULL,
  `UpdateDate` DATETIME NOT NULL,
  `State` BIT NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Detail_UNIQUE` (`Detail` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Person` (
  `Id` VARCHAR(50) NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `FirstLastName` VARCHAR(45) NOT NULL,
  `SecondLastName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Name_UNIQUE` (`Name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `Name` NVARCHAR(150) NOT NULL,
  `Password` NVARCHAR(150) NOT NULL,
  `UserType_Id` INT NOT NULL,
  `Person_Id` VARCHAR(50) NOT NULL,
  `Date` DATETIME NOT NULL,
  `UpdateDate` DATETIME NOT NULL,
  `State` BIT NOT NULL,
  PRIMARY KEY (`Name`),
  INDEX `fk_User_catalog_UserType_idx` (`UserType_Id` ASC) VISIBLE,
  INDEX `fk_User_Person1_idx` (`Person_Id` ASC) VISIBLE,
  CONSTRAINT `fk_User_catalog_UserType`
    FOREIGN KEY (`UserType_Id`)
    REFERENCES `mydb`.`catalog_UserType` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_Person1`
    FOREIGN KEY (`Person_Id`)
    REFERENCES `mydb`.`Person` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`catalog_SoftSkills`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`catalog_SoftSkills` (
  `Id` INT NOT NULL,
  `Detail` VARCHAR(100) NOT NULL,
  `Date` DATETIME NOT NULL,
  `UpdateDate` DATETIME NOT NULL,
  `State` BIT NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Detail_UNIQUE` (`Detail` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`catalog_RegexType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`catalog_RegexType` (
  `Id` INT NOT NULL,
  `Detail` VARCHAR(100) NOT NULL,
  `Regex` VARCHAR(200) NOT NULL,
  `Date` DATETIME NOT NULL,
  `UpdateDate` DATETIME NOT NULL,
  `State` BIT NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Detail_UNIQUE` (`Detail` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`catalog_ContactType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`catalog_ContactType` (
  `Id` INT NOT NULL,
  `RegexType_Id` INT NOT NULL,
  `Detail` VARCHAR(100) NOT NULL,
  `Regex` VARCHAR(100) NULL,
  `Date` DATETIME NOT NULL,
  `UpdateDate` DATETIME NOT NULL,
  `State` BIT NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Detail_UNIQUE` (`Detail` ASC) VISIBLE,
  INDEX `fk_catalog_ContactType_catalog_RegexType1_idx` (`RegexType_Id` ASC) VISIBLE,
  CONSTRAINT `fk_catalog_ContactType_catalog_RegexType1`
    FOREIGN KEY (`RegexType_Id`)
    REFERENCES `mydb`.`catalog_RegexType` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Contact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Contact` (
  `Data` VARCHAR(300) NOT NULL,
  `Person_Id` VARCHAR(50) NOT NULL,
  `Date` DATETIME NOT NULL,
  `UpdateDate` DATETIME NOT NULL,
  `State` BIT NOT NULL,
  `ContactType_Id` INT NOT NULL,
  PRIMARY KEY (`Data`, `Person_Id`),
  INDEX `fk_Contact_Person1_idx` (`Person_Id` ASC) VISIBLE,
  INDEX `fk_Contact_catalog_ContactType1_idx` (`ContactType_Id` ASC) VISIBLE,
  CONSTRAINT `fk_Contact_Person1`
    FOREIGN KEY (`Person_Id`)
    REFERENCES `mydb`.`Person` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Contact_catalog_ContactType1`
    FOREIGN KEY (`ContactType_Id`)
    REFERENCES `mydb`.`catalog_ContactType` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User_has_SoftSkills`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User_has_SoftSkills` (
  `User_Name` NVARCHAR(150) NOT NULL,
  `SoftSkills_Id` INT NOT NULL,
  `State` BIT NOT NULL,
  PRIMARY KEY (`User_Name`, `SoftSkills_Id`),
  INDEX `fk_User_has_catalog_SoftSkills_catalog_SoftSkills1_idx` (`SoftSkills_Id` ASC) VISIBLE,
  INDEX `fk_User_has_catalog_SoftSkills_User1_idx` (`User_Name` ASC) VISIBLE,
  CONSTRAINT `fk_User_has_catalog_SoftSkills_User1`
    FOREIGN KEY (`User_Name`)
    REFERENCES `mydb`.`User` (`Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_catalog_SoftSkills_catalog_SoftSkills1`
    FOREIGN KEY (`SoftSkills_Id`)
    REFERENCES `mydb`.`catalog_SoftSkills` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
